spring:
  config:
    import:
      - optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate # 공용 DB는 테이블 구조 확정되면  validate