-- Public numeric POI id for app/API requests while keeping the UUID primary key.

ALTER TABLE poi
    ADD COLUMN public_id bigint GENERATED BY DEFAULT AS IDENTITY;

UPDATE poi
SET public_id = nextval(pg_get_serial_sequence('poi', 'public_id'))
WHERE public_id IS NULL;

ALTER TABLE poi
    ALTER COLUMN public_id SET NOT NULL;

ALTER TABLE poi
    ADD CONSTRAINT uq_poi_public_id UNIQUE (public_id);

CREATE INDEX poi_public_id_idx ON poi (public_id);
